global using Amazon;
global using Amazon.S3;
global using Amazon.S3.Model;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using Shelly.ProviderBlobStorages.Helper;
global using Shelly.ProviderBlobStorages.Interface;
global using Shelly.Abstractions.Settings.Options;
global using Shelly.ProviderBlobStorages.Services;